export interface DeclarationDto {
    id: number,
    dispatch_date : string,
    number_packages : number,
    idcustoms : number,
    total_units : number,
    idconsignee : number,
    gross_kilos : number,
    idshippingtype : number,
    fob : number,
    fob_bills : number,
    freight : number,
    sure : number,
    idinsurancecarrier: number,
    iddispatcher : number,
    idcategories : number,
    customer_reference : string,
    idtransportroute : number,
    idcarrier : number,
    iddeposit : number,
    idimporterrisk : number,
    idshipper : number,
    idsender : number,
    contents : string,
    idtechnical : null,
    idcommissionagent : null,
    electronicpayment : null,
    date_preliquidation : string,
    series_number : number,
    type_proration : number,
    nombre : string,
    dni: string,
    ruc: string,
    departamento: string,
    provincia: string,
    distrito: string,
    direccion : string,
    cod_customs : string,
    customs : string,


}